name: CI

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    branches:
      - develop
    paths-ignore:
      - README.md
      - LICENSE

env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app

jobs:
  test:
    runs-on: macOS-latest

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # 単体テストの実行
    - name: Xcode test
      run: make test

    # 単体テストログのアップロード
    - name: Upload test log Artifact
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: xcodebuild-logs
        path: xcodebuild_test.log
        if-no-files-found: ignore
        retention-days: 14
